[tool.poetry]
name = "hhcli"
version = "0.4.0"
description = "Консольная утилита для удобного поиска вакансий и откликов на hh.ru."
authors = ["Your Name <you@example.com>"]
readme = "README.md"
license = "MIT"
packages = [{include = "hhcli"}]
include = ["hhcli/ui/styles.tcss"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
flask = "^3.0.0"
platformdirs = "^4.0.0"
sqlalchemy = "^2.0.23"
textual = "^0.43.0"
html2text = "^2025.4.15"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.6"
pytest = "^7.4.3"

[tool.poetry.scripts]
hhcli = "hhcli.main:run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.main:api"
